import { SubAdmin } from "../list/types/subAdmin";

const subAdminsData: SubAdmin[] = [
  {
    id: "1",
    name: "Jeel",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeel1&backgroundColor=b6e3f4",
  },
  {
    id: "2",
    name: "Meet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meet&backgroundColor=ffdfbf",
  },
  {
    id: "3",
    name: "Deep",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Deep&backgroundColor=c0aede",
  },
  {
    id: "4",
    name: "Jeet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeet&backgroundColor=d1d4f9",
  },
  {
    id: "5",
    name: "Jeel",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeel2&backgroundColor=ffd5dc",
  },
  {
    id: "6",
    name: "Meet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meet2&backgroundColor=ffe4b5",
  },
  {
    id: "7",
    name: "Deep",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Deep2&backgroundColor=e0e0e0",
  },
  {
    id: "8",
    name: "Jeet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeet2&backgroundColor=d4a5ff",
  },
  {
    id: "9",
    name: "Jeel",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeel3&backgroundColor=a8dadc",
  },
  {
    id: "10",
    name: "Meet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meet3&backgroundColor=f1c0e8",
  },
];