import { SubAdmin } from "../types/subAdmin";

export const subAdminsData: SubAdmin[] = [
  {
    id: "1",
    name: "Jeel",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeel1&backgroundColor=b6e3f4",
  },
  {
    id: "2",
    name: "Meet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meet&backgroundColor=ffdfbf",
  },
  {
    id: "3",
    name: "Deep",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Deep&backgroundColor=c0aede",
  },
  {
    id: "4",
    name: "Jeet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeet&backgroundColor=d1d4f9",
  },
  {
    id: "5",
    name: "Jeel",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeel2&backgroundColor=ffd5dc",
  },
  {
    id: "6",
    name: "Meet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meet2&backgroundColor=ffe4b5",
  },
  {
    id: "7",
    name: "Deep",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Deep2&backgroundColor=e0e0e0",
  },
  {
    id: "8",
    name: "Jeet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeet2&backgroundColor=d4a5ff",
  },
  {
    id: "9",
    name: "Jeel",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jeel3&backgroundColor=a8dadc",
  },
  {
    id: "10",
    name: "Meet",
    email: "exp@mail.com",
    mobile: "+91 9876543210",
    role: "Finance",
    dateOfCreation: "Mar 25, 2025",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meet3&backgroundColor=f1c0e8",
  },
];



// Add this to your utils/dummyData.ts file

export const logsData = [
  {
    id: "1",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 25, 2025, 11:43 AM",
  },
  {
    id: "2",
    title: "Updated Vendor Information",
    module: "Vendors",
    when: "Mar 25, 2025, 11:30 AM",
  },
  {
    id: "3",
    title: "Deleted Purchase Order",
    module: "Purchase Orders",
    when: "Mar 25, 2025, 11:15 AM",
  },
  {
    id: "4",
    title: "Created New Invoice",
    module: "Invoices",
    when: "Mar 25, 2025, 11:00 AM",
  },
  {
    id: "5",
    title: "Updated Payment Status",
    module: "Payments",
    when: "Mar 25, 2025, 10:45 AM",
  },
  {
    id: "6",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 25, 2025, 10:30 AM",
  },
  {
    id: "7",
    title: "Approved Budget Request",
    module: "Finance",
    when: "Mar 25, 2025, 10:15 AM",
  },
  {
    id: "8",
    title: "Modified User Permissions",
    module: "Settings",
    when: "Mar 25, 2025, 10:00 AM",
  },
  {
    id: "9",
    title: "Generated Financial Report",
    module: "Reports",
    when: "Mar 25, 2025, 09:45 AM",
  },
  {
    id: "10",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 25, 2025, 09:30 AM",
  },
  {
    id: "11",
    title: "Updated Inventory Count",
    module: "Inventory",
    when: "Mar 25, 2025, 09:15 AM",
  },
  {
    id: "12",
    title: "Created Purchase Request",
    module: "Purchase Orders",
    when: "Mar 25, 2025, 09:00 AM",
  },
  {
    id: "13",
    title: "Deleted Expired Document",
    module: "Documents",
    when: "Mar 24, 2025, 05:30 PM",
  },
  {
    id: "14",
    title: "Updated Tax Configuration",
    module: "Finance",
    when: "Mar 24, 2025, 05:15 PM",
  },
  {
    id: "15",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 24, 2025, 05:00 PM",
  },
  {
    id: "16",
    title: "Approved Expense Claim",
    module: "Expenses",
    when: "Mar 24, 2025, 04:45 PM",
  },
  {
    id: "17",
    title: "Created New Customer",
    module: "Customers",
    when: "Mar 24, 2025, 04:30 PM",
  },
  {
    id: "18",
    title: "Updated Product Pricing",
    module: "Products",
    when: "Mar 24, 2025, 04:15 PM",
  },
  {
    id: "19",
    title: "Generated Sales Report",
    module: "Reports",
    when: "Mar 24, 2025, 04:00 PM",
  },
  {
    id: "20",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 24, 2025, 03:45 PM",
  },
  {
    id: "21",
    title: "Updated Shipping Details",
    module: "Orders",
    when: "Mar 24, 2025, 03:30 PM",
  },
  {
    id: "22",
    title: "Processed Refund Request",
    module: "Payments",
    when: "Mar 24, 2025, 03:15 PM",
  },
  {
    id: "23",
    title: "Added New Employee",
    module: "HR",
    when: "Mar 24, 2025, 03:00 PM",
  },
  {
    id: "24",
    title: "Updated System Settings",
    module: "Settings",
    when: "Mar 24, 2025, 02:45 PM",
  },
  {
    id: "25",
    title: "Created Asset Record",
    module: "Assets",
    when: "Mar 24, 2025, 02:30 PM",
  },
  {
    id: "26",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 24, 2025, 02:15 PM",
  },
  {
    id: "27",
    title: "Updated Contract Terms",
    module: "Contracts",
    when: "Mar 24, 2025, 02:00 PM",
  },
  {
    id: "28",
    title: "Approved Leave Request",
    module: "HR",
    when: "Mar 24, 2025, 01:45 PM",
  },
  {
    id: "29",
    title: "Generated Payroll Report",
    module: "Finance",
    when: "Mar 24, 2025, 01:30 PM",
  },
  {
    id: "30",
    title: "Added a new Vendor",
    module: "Vendors",
    when: "Mar 24, 2025, 01:15 PM",
  },
  {
    id: "31",
    title: "Updated Warehouse Location",
    module: "Inventory",
    when: "Mar 24, 2025, 01:00 PM",
  },
  {
    id: "32",
    title: "Created Maintenance Request",
    module: "Maintenance",
    when: "Mar 24, 2025, 12:45 PM",
  },
];