/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppVendorsRouteRouteImport } from './routes/_app/vendors/route'
import { Route as AppSubAdminRouteRouteImport } from './routes/_app/sub-admin/route'
import { Route as AppProfileRouteRouteImport } from './routes/_app/profile/route'
import { Route as AppCmsRouteRouteImport } from './routes/_app/cms/route'
import { Route as AppCategoriesRouteRouteImport } from './routes/_app/categories/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthScrollIndexRouteImport } from './routes/_auth/scroll/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AppWarehousesIndexRouteImport } from './routes/_app/warehouses/index'
import { Route as AppWarehouseIndexRouteImport } from './routes/_app/warehouse/index'
import { Route as AppVendorsIndexRouteImport } from './routes/_app/vendors/index'
import { Route as AppUgcCampaignsIndexRouteImport } from './routes/_app/ugc-campaigns/index'
import { Route as AppTiersIndexRouteImport } from './routes/_app/tiers/index'
import { Route as AppSubAdminIndexRouteImport } from './routes/_app/sub-admin/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppPromoteProductsIndexRouteImport } from './routes/_app/promote-products/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppDiscountsIndexRouteImport } from './routes/_app/discounts/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as AppAlertsIndexRouteImport } from './routes/_app/alerts/index'
import { Route as AppWarehousesWarehouseIdRouteImport } from './routes/_app/warehouses/$warehouseId'
import { Route as AppVendorsVendorIdRouteImport } from './routes/_app/vendors/$vendorId'
import { Route as AppOrdersSplatRouteImport } from './routes/_app/orders/$'
import { Route as AppCoinsSplatRouteImport } from './routes/_app/coins/$'
import { Route as AppWarehousesCreateRouteRouteImport } from './routes/_app/warehouses/create/route'
import { Route as AppTiersCreateRouteRouteImport } from './routes/_app/tiers/create/route'
import { Route as AppSubAdminSubAdminDetailsRouteRouteImport } from './routes/_app/sub-admin/sub-admin-details/route'
import { Route as AppSubAdminRolesPermissionsRouteRouteImport } from './routes/_app/sub-admin/roles-permissions/route'
import { Route as AppSubAdminCreateAdminRouteRouteImport } from './routes/_app/sub-admin/create-admin/route'
import { Route as AppProductsRequestsRouteRouteImport } from './routes/_app/products/requests/route'
import { Route as AppProductsProductsListRouteRouteImport } from './routes/_app/products/products-list/route'
import { Route as AppCmsBannersRouteRouteImport } from './routes/_app/cms/banners/route'
import { Route as AppCategoriesCreateRouteRouteImport } from './routes/_app/categories/create/route'
import { Route as AppVendorsVendorDetailsIndexRouteImport } from './routes/_app/vendors/vendor-details/index'
import { Route as AppSubAdminRolesPermissionsIndexRouteImport } from './routes/_app/sub-admin/roles-permissions/index'
import { Route as AppProductsListIndexRouteImport } from './routes/_app/products/list/index'
import { Route as AppProductsAddIndexRouteImport } from './routes/_app/products/add/index'
import { Route as AppOrdersPayment_confirmedIndexRouteImport } from './routes/_app/orders/payment_confirmed/index'
import { Route as AppOrdersInitiatedIndexRouteImport } from './routes/_app/orders/initiated/index'
import { Route as AppOrdersAllIndexRouteImport } from './routes/_app/orders/all/index'
import { Route as AppCoinsTransactionsIndexRouteImport } from './routes/_app/coins/transactions/index'
import { Route as AppCoinsSummaryIndexRouteImport } from './routes/_app/coins/summary/index'
import { Route as AppCmsSectionsIndexRouteImport } from './routes/_app/cms/sections/index'
import { Route as AppCmsHomeIndexRouteImport } from './routes/_app/cms/home/index'
import { Route as AppCmsBannersIndexRouteImport } from './routes/_app/cms/banners/index'
import { Route as AppWarehousesEditWarehouseIdRouteImport } from './routes/_app/warehouses/edit.$warehouseId'
import { Route as AppTiersTierIdEditRouteImport } from './routes/_app/tiers/$tierId.edit'
import { Route as AppCmsHomeCreateRouteImport } from './routes/_app/cms/home/create'
import { Route as AppCategoriesCategoryIdViewRouteImport } from './routes/_app/categories/$categoryId.view'
import { Route as AppCategoriesCategoryIdEditRouteImport } from './routes/_app/categories/$categoryId.edit'
import { Route as AppSubAdminSubAdminDetailsIdRouteRouteImport } from './routes/_app/sub-admin/sub-admin-details/$id/route'
import { Route as AppSubAdminRolesPermissionsCreateRouteRouteImport } from './routes/_app/sub-admin/roles-permissions/create/route'
import { Route as AppSubAdminRolesPermissionsIdRouteRouteImport } from './routes/_app/sub-admin/roles-permissions/$id/route'
import { Route as AppCmsSectionsCreateRouteRouteImport } from './routes/_app/cms/sections/create/route'
import { Route as AppCmsBannersCreateRouteRouteImport } from './routes/_app/cms/banners/create/route'
import { Route as AppCmsSectionsSectionIdEditRouteImport } from './routes/_app/cms/sections/$sectionId.edit'
import { Route as AppCmsHomeEditHomeIdRouteImport } from './routes/_app/cms/home/edit/$homeId'
import { Route as AppCmsBannersEditBannerIdRouteImport } from './routes/_app/cms/banners/edit/$bannerId'
import { Route as AppSubAdminRolesPermissionsIdEditRouteRouteImport } from './routes/_app/sub-admin/roles-permissions/$id/edit/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendorsRouteRoute = AppVendorsRouteRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubAdminRouteRoute = AppSubAdminRouteRouteImport.update({
  id: '/sub-admin',
  path: '/sub-admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCmsRouteRoute = AppCmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRouteRoute = AppCategoriesRouteRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthScrollIndexRoute = AuthScrollIndexRouteImport.update({
  id: '/scroll/',
  path: '/scroll/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWarehousesIndexRoute = AppWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWarehouseIndexRoute = AppWarehouseIndexRouteImport.update({
  id: '/warehouse/',
  path: '/warehouse/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorsRouteRoute,
} as any)
const AppUgcCampaignsIndexRoute = AppUgcCampaignsIndexRouteImport.update({
  id: '/ugc-campaigns/',
  path: '/ugc-campaigns/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTiersIndexRoute = AppTiersIndexRouteImport.update({
  id: '/tiers/',
  path: '/tiers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubAdminIndexRoute = AppSubAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubAdminRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPromoteProductsIndexRoute = AppPromoteProductsIndexRouteImport.update({
  id: '/promote-products/',
  path: '/promote-products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscountsIndexRoute = AppDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCategoriesRouteRoute,
} as any)
const AppAlertsIndexRoute = AppAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWarehousesWarehouseIdRoute =
  AppWarehousesWarehouseIdRouteImport.update({
    id: '/warehouses/$warehouseId',
    path: '/warehouses/$warehouseId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppVendorsVendorIdRoute = AppVendorsVendorIdRouteImport.update({
  id: '/$vendorId',
  path: '/$vendorId',
  getParentRoute: () => AppVendorsRouteRoute,
} as any)
const AppOrdersSplatRoute = AppOrdersSplatRouteImport.update({
  id: '/orders/$',
  path: '/orders/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoinsSplatRoute = AppCoinsSplatRouteImport.update({
  id: '/coins/$',
  path: '/coins/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWarehousesCreateRouteRoute =
  AppWarehousesCreateRouteRouteImport.update({
    id: '/warehouses/create',
    path: '/warehouses/create',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppTiersCreateRouteRoute = AppTiersCreateRouteRouteImport.update({
  id: '/tiers/create',
  path: '/tiers/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSubAdminSubAdminDetailsRouteRoute =
  AppSubAdminSubAdminDetailsRouteRouteImport.update({
    id: '/sub-admin-details',
    path: '/sub-admin-details',
    getParentRoute: () => AppSubAdminRouteRoute,
  } as any)
const AppSubAdminRolesPermissionsRouteRoute =
  AppSubAdminRolesPermissionsRouteRouteImport.update({
    id: '/roles-permissions',
    path: '/roles-permissions',
    getParentRoute: () => AppSubAdminRouteRoute,
  } as any)
const AppSubAdminCreateAdminRouteRoute =
  AppSubAdminCreateAdminRouteRouteImport.update({
    id: '/create-admin',
    path: '/create-admin',
    getParentRoute: () => AppSubAdminRouteRoute,
  } as any)
const AppProductsRequestsRouteRoute =
  AppProductsRequestsRouteRouteImport.update({
    id: '/products/requests',
    path: '/products/requests',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppProductsProductsListRouteRoute =
  AppProductsProductsListRouteRouteImport.update({
    id: '/products/products-list',
    path: '/products/products-list',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCmsBannersRouteRoute = AppCmsBannersRouteRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AppCmsRouteRoute,
} as any)
const AppCategoriesCreateRouteRoute =
  AppCategoriesCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppCategoriesRouteRoute,
  } as any)
const AppVendorsVendorDetailsIndexRoute =
  AppVendorsVendorDetailsIndexRouteImport.update({
    id: '/vendor-details/',
    path: '/vendor-details/',
    getParentRoute: () => AppVendorsRouteRoute,
  } as any)
const AppSubAdminRolesPermissionsIndexRoute =
  AppSubAdminRolesPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSubAdminRolesPermissionsRouteRoute,
  } as any)
const AppProductsListIndexRoute = AppProductsListIndexRouteImport.update({
  id: '/products/list/',
  path: '/products/list/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsAddIndexRoute = AppProductsAddIndexRouteImport.update({
  id: '/products/add/',
  path: '/products/add/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersPayment_confirmedIndexRoute =
  AppOrdersPayment_confirmedIndexRouteImport.update({
    id: '/orders/payment_confirmed/',
    path: '/orders/payment_confirmed/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrdersInitiatedIndexRoute = AppOrdersInitiatedIndexRouteImport.update({
  id: '/orders/initiated/',
  path: '/orders/initiated/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersAllIndexRoute = AppOrdersAllIndexRouteImport.update({
  id: '/orders/all/',
  path: '/orders/all/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoinsTransactionsIndexRoute =
  AppCoinsTransactionsIndexRouteImport.update({
    id: '/coins/transactions/',
    path: '/coins/transactions/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCoinsSummaryIndexRoute = AppCoinsSummaryIndexRouteImport.update({
  id: '/coins/summary/',
  path: '/coins/summary/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCmsSectionsIndexRoute = AppCmsSectionsIndexRouteImport.update({
  id: '/sections/',
  path: '/sections/',
  getParentRoute: () => AppCmsRouteRoute,
} as any)
const AppCmsHomeIndexRoute = AppCmsHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppCmsRouteRoute,
} as any)
const AppCmsBannersIndexRoute = AppCmsBannersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCmsBannersRouteRoute,
} as any)
const AppWarehousesEditWarehouseIdRoute =
  AppWarehousesEditWarehouseIdRouteImport.update({
    id: '/warehouses/edit/$warehouseId',
    path: '/warehouses/edit/$warehouseId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppTiersTierIdEditRoute = AppTiersTierIdEditRouteImport.update({
  id: '/tiers/$tierId/edit',
  path: '/tiers/$tierId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCmsHomeCreateRoute = AppCmsHomeCreateRouteImport.update({
  id: '/home/create',
  path: '/home/create',
  getParentRoute: () => AppCmsRouteRoute,
} as any)
const AppCategoriesCategoryIdViewRoute =
  AppCategoriesCategoryIdViewRouteImport.update({
    id: '/$categoryId/view',
    path: '/$categoryId/view',
    getParentRoute: () => AppCategoriesRouteRoute,
  } as any)
const AppCategoriesCategoryIdEditRoute =
  AppCategoriesCategoryIdEditRouteImport.update({
    id: '/$categoryId/edit',
    path: '/$categoryId/edit',
    getParentRoute: () => AppCategoriesRouteRoute,
  } as any)
const AppSubAdminSubAdminDetailsIdRouteRoute =
  AppSubAdminSubAdminDetailsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppSubAdminSubAdminDetailsRouteRoute,
  } as any)
const AppSubAdminRolesPermissionsCreateRouteRoute =
  AppSubAdminRolesPermissionsCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppSubAdminRolesPermissionsRouteRoute,
  } as any)
const AppSubAdminRolesPermissionsIdRouteRoute =
  AppSubAdminRolesPermissionsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppSubAdminRolesPermissionsRouteRoute,
  } as any)
const AppCmsSectionsCreateRouteRoute =
  AppCmsSectionsCreateRouteRouteImport.update({
    id: '/sections/create',
    path: '/sections/create',
    getParentRoute: () => AppCmsRouteRoute,
  } as any)
const AppCmsBannersCreateRouteRoute =
  AppCmsBannersCreateRouteRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppCmsBannersRouteRoute,
  } as any)
const AppCmsSectionsSectionIdEditRoute =
  AppCmsSectionsSectionIdEditRouteImport.update({
    id: '/sections/$sectionId/edit',
    path: '/sections/$sectionId/edit',
    getParentRoute: () => AppCmsRouteRoute,
  } as any)
const AppCmsHomeEditHomeIdRoute = AppCmsHomeEditHomeIdRouteImport.update({
  id: '/home/edit/$homeId',
  path: '/home/edit/$homeId',
  getParentRoute: () => AppCmsRouteRoute,
} as any)
const AppCmsBannersEditBannerIdRoute =
  AppCmsBannersEditBannerIdRouteImport.update({
    id: '/edit/$bannerId',
    path: '/edit/$bannerId',
    getParentRoute: () => AppCmsBannersRouteRoute,
  } as any)
const AppSubAdminRolesPermissionsIdEditRouteRoute =
  AppSubAdminRolesPermissionsIdEditRouteRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppSubAdminRolesPermissionsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AppAdminRouteRoute
  '/categories': typeof AppCategoriesRouteRouteWithChildren
  '/cms': typeof AppCmsRouteRouteWithChildren
  '/profile': typeof AppProfileRouteRoute
  '/sub-admin': typeof AppSubAdminRouteRouteWithChildren
  '/vendors': typeof AppVendorsRouteRouteWithChildren
  '/$': typeof AppSplatRoute
  '/categories/create': typeof AppCategoriesCreateRouteRoute
  '/cms/banners': typeof AppCmsBannersRouteRouteWithChildren
  '/products/products-list': typeof AppProductsProductsListRouteRoute
  '/products/requests': typeof AppProductsRequestsRouteRoute
  '/sub-admin/create-admin': typeof AppSubAdminCreateAdminRouteRoute
  '/sub-admin/roles-permissions': typeof AppSubAdminRolesPermissionsRouteRouteWithChildren
  '/sub-admin/sub-admin-details': typeof AppSubAdminSubAdminDetailsRouteRouteWithChildren
  '/tiers/create': typeof AppTiersCreateRouteRoute
  '/warehouses/create': typeof AppWarehousesCreateRouteRoute
  '/coins/$': typeof AppCoinsSplatRoute
  '/orders/$': typeof AppOrdersSplatRoute
  '/vendors/$vendorId': typeof AppVendorsVendorIdRoute
  '/warehouses/$warehouseId': typeof AppWarehousesWarehouseIdRoute
  '/alerts': typeof AppAlertsIndexRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/discounts': typeof AppDiscountsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/promote-products': typeof AppPromoteProductsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sub-admin/': typeof AppSubAdminIndexRoute
  '/tiers': typeof AppTiersIndexRoute
  '/ugc-campaigns': typeof AppUgcCampaignsIndexRoute
  '/vendors/': typeof AppVendorsIndexRoute
  '/warehouse': typeof AppWarehouseIndexRoute
  '/warehouses': typeof AppWarehousesIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/scroll': typeof AuthScrollIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/cms/banners/create': typeof AppCmsBannersCreateRouteRoute
  '/cms/sections/create': typeof AppCmsSectionsCreateRouteRoute
  '/sub-admin/roles-permissions/$id': typeof AppSubAdminRolesPermissionsIdRouteRouteWithChildren
  '/sub-admin/roles-permissions/create': typeof AppSubAdminRolesPermissionsCreateRouteRoute
  '/sub-admin/sub-admin-details/$id': typeof AppSubAdminSubAdminDetailsIdRouteRoute
  '/categories/$categoryId/edit': typeof AppCategoriesCategoryIdEditRoute
  '/categories/$categoryId/view': typeof AppCategoriesCategoryIdViewRoute
  '/cms/home/create': typeof AppCmsHomeCreateRoute
  '/tiers/$tierId/edit': typeof AppTiersTierIdEditRoute
  '/warehouses/edit/$warehouseId': typeof AppWarehousesEditWarehouseIdRoute
  '/cms/banners/': typeof AppCmsBannersIndexRoute
  '/cms/home': typeof AppCmsHomeIndexRoute
  '/cms/sections': typeof AppCmsSectionsIndexRoute
  '/coins/summary': typeof AppCoinsSummaryIndexRoute
  '/coins/transactions': typeof AppCoinsTransactionsIndexRoute
  '/orders/all': typeof AppOrdersAllIndexRoute
  '/orders/initiated': typeof AppOrdersInitiatedIndexRoute
  '/orders/payment_confirmed': typeof AppOrdersPayment_confirmedIndexRoute
  '/products/add': typeof AppProductsAddIndexRoute
  '/products/list': typeof AppProductsListIndexRoute
  '/sub-admin/roles-permissions/': typeof AppSubAdminRolesPermissionsIndexRoute
  '/vendors/vendor-details': typeof AppVendorsVendorDetailsIndexRoute
  '/sub-admin/roles-permissions/$id/edit': typeof AppSubAdminRolesPermissionsIdEditRouteRoute
  '/cms/banners/edit/$bannerId': typeof AppCmsBannersEditBannerIdRoute
  '/cms/home/edit/$homeId': typeof AppCmsHomeEditHomeIdRoute
  '/cms/sections/$sectionId/edit': typeof AppCmsSectionsSectionIdEditRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRouteRoute
  '/cms': typeof AppCmsRouteRouteWithChildren
  '/profile': typeof AppProfileRouteRoute
  '/$': typeof AppSplatRoute
  '/categories/create': typeof AppCategoriesCreateRouteRoute
  '/products/products-list': typeof AppProductsProductsListRouteRoute
  '/products/requests': typeof AppProductsRequestsRouteRoute
  '/sub-admin/create-admin': typeof AppSubAdminCreateAdminRouteRoute
  '/sub-admin/sub-admin-details': typeof AppSubAdminSubAdminDetailsRouteRouteWithChildren
  '/tiers/create': typeof AppTiersCreateRouteRoute
  '/warehouses/create': typeof AppWarehousesCreateRouteRoute
  '/coins/$': typeof AppCoinsSplatRoute
  '/orders/$': typeof AppOrdersSplatRoute
  '/vendors/$vendorId': typeof AppVendorsVendorIdRoute
  '/warehouses/$warehouseId': typeof AppWarehousesWarehouseIdRoute
  '/alerts': typeof AppAlertsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/discounts': typeof AppDiscountsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/promote-products': typeof AppPromoteProductsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sub-admin': typeof AppSubAdminIndexRoute
  '/tiers': typeof AppTiersIndexRoute
  '/ugc-campaigns': typeof AppUgcCampaignsIndexRoute
  '/vendors': typeof AppVendorsIndexRoute
  '/warehouse': typeof AppWarehouseIndexRoute
  '/warehouses': typeof AppWarehousesIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/scroll': typeof AuthScrollIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/cms/banners/create': typeof AppCmsBannersCreateRouteRoute
  '/cms/sections/create': typeof AppCmsSectionsCreateRouteRoute
  '/sub-admin/roles-permissions/$id': typeof AppSubAdminRolesPermissionsIdRouteRouteWithChildren
  '/sub-admin/roles-permissions/create': typeof AppSubAdminRolesPermissionsCreateRouteRoute
  '/sub-admin/sub-admin-details/$id': typeof AppSubAdminSubAdminDetailsIdRouteRoute
  '/categories/$categoryId/edit': typeof AppCategoriesCategoryIdEditRoute
  '/categories/$categoryId/view': typeof AppCategoriesCategoryIdViewRoute
  '/cms/home/create': typeof AppCmsHomeCreateRoute
  '/tiers/$tierId/edit': typeof AppTiersTierIdEditRoute
  '/warehouses/edit/$warehouseId': typeof AppWarehousesEditWarehouseIdRoute
  '/cms/banners': typeof AppCmsBannersIndexRoute
  '/cms/home': typeof AppCmsHomeIndexRoute
  '/cms/sections': typeof AppCmsSectionsIndexRoute
  '/coins/summary': typeof AppCoinsSummaryIndexRoute
  '/coins/transactions': typeof AppCoinsTransactionsIndexRoute
  '/orders/all': typeof AppOrdersAllIndexRoute
  '/orders/initiated': typeof AppOrdersInitiatedIndexRoute
  '/orders/payment_confirmed': typeof AppOrdersPayment_confirmedIndexRoute
  '/products/add': typeof AppProductsAddIndexRoute
  '/products/list': typeof AppProductsListIndexRoute
  '/sub-admin/roles-permissions': typeof AppSubAdminRolesPermissionsIndexRoute
  '/vendors/vendor-details': typeof AppVendorsVendorDetailsIndexRoute
  '/sub-admin/roles-permissions/$id/edit': typeof AppSubAdminRolesPermissionsIdEditRouteRoute
  '/cms/banners/edit/$bannerId': typeof AppCmsBannersEditBannerIdRoute
  '/cms/home/edit/$homeId': typeof AppCmsHomeEditHomeIdRoute
  '/cms/sections/$sectionId/edit': typeof AppCmsSectionsSectionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRouteRoute
  '/_app/categories': typeof AppCategoriesRouteRouteWithChildren
  '/_app/cms': typeof AppCmsRouteRouteWithChildren
  '/_app/profile': typeof AppProfileRouteRoute
  '/_app/sub-admin': typeof AppSubAdminRouteRouteWithChildren
  '/_app/vendors': typeof AppVendorsRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_app/categories/create': typeof AppCategoriesCreateRouteRoute
  '/_app/cms/banners': typeof AppCmsBannersRouteRouteWithChildren
  '/_app/products/products-list': typeof AppProductsProductsListRouteRoute
  '/_app/products/requests': typeof AppProductsRequestsRouteRoute
  '/_app/sub-admin/create-admin': typeof AppSubAdminCreateAdminRouteRoute
  '/_app/sub-admin/roles-permissions': typeof AppSubAdminRolesPermissionsRouteRouteWithChildren
  '/_app/sub-admin/sub-admin-details': typeof AppSubAdminSubAdminDetailsRouteRouteWithChildren
  '/_app/tiers/create': typeof AppTiersCreateRouteRoute
  '/_app/warehouses/create': typeof AppWarehousesCreateRouteRoute
  '/_app/coins/$': typeof AppCoinsSplatRoute
  '/_app/orders/$': typeof AppOrdersSplatRoute
  '/_app/vendors/$vendorId': typeof AppVendorsVendorIdRoute
  '/_app/warehouses/$warehouseId': typeof AppWarehousesWarehouseIdRoute
  '/_app/alerts/': typeof AppAlertsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/discounts/': typeof AppDiscountsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/promote-products/': typeof AppPromoteProductsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sub-admin/': typeof AppSubAdminIndexRoute
  '/_app/tiers/': typeof AppTiersIndexRoute
  '/_app/ugc-campaigns/': typeof AppUgcCampaignsIndexRoute
  '/_app/vendors/': typeof AppVendorsIndexRoute
  '/_app/warehouse/': typeof AppWarehouseIndexRoute
  '/_app/warehouses/': typeof AppWarehousesIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/scroll/': typeof AuthScrollIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_app/cms/banners/create': typeof AppCmsBannersCreateRouteRoute
  '/_app/cms/sections/create': typeof AppCmsSectionsCreateRouteRoute
  '/_app/sub-admin/roles-permissions/$id': typeof AppSubAdminRolesPermissionsIdRouteRouteWithChildren
  '/_app/sub-admin/roles-permissions/create': typeof AppSubAdminRolesPermissionsCreateRouteRoute
  '/_app/sub-admin/sub-admin-details/$id': typeof AppSubAdminSubAdminDetailsIdRouteRoute
  '/_app/categories/$categoryId/edit': typeof AppCategoriesCategoryIdEditRoute
  '/_app/categories/$categoryId/view': typeof AppCategoriesCategoryIdViewRoute
  '/_app/cms/home/create': typeof AppCmsHomeCreateRoute
  '/_app/tiers/$tierId/edit': typeof AppTiersTierIdEditRoute
  '/_app/warehouses/edit/$warehouseId': typeof AppWarehousesEditWarehouseIdRoute
  '/_app/cms/banners/': typeof AppCmsBannersIndexRoute
  '/_app/cms/home/': typeof AppCmsHomeIndexRoute
  '/_app/cms/sections/': typeof AppCmsSectionsIndexRoute
  '/_app/coins/summary/': typeof AppCoinsSummaryIndexRoute
  '/_app/coins/transactions/': typeof AppCoinsTransactionsIndexRoute
  '/_app/orders/all/': typeof AppOrdersAllIndexRoute
  '/_app/orders/initiated/': typeof AppOrdersInitiatedIndexRoute
  '/_app/orders/payment_confirmed/': typeof AppOrdersPayment_confirmedIndexRoute
  '/_app/products/add/': typeof AppProductsAddIndexRoute
  '/_app/products/list/': typeof AppProductsListIndexRoute
  '/_app/sub-admin/roles-permissions/': typeof AppSubAdminRolesPermissionsIndexRoute
  '/_app/vendors/vendor-details/': typeof AppVendorsVendorDetailsIndexRoute
  '/_app/sub-admin/roles-permissions/$id/edit': typeof AppSubAdminRolesPermissionsIdEditRouteRoute
  '/_app/cms/banners/edit/$bannerId': typeof AppCmsBannersEditBannerIdRoute
  '/_app/cms/home/edit/$homeId': typeof AppCmsHomeEditHomeIdRoute
  '/_app/cms/sections/$sectionId/edit': typeof AppCmsSectionsSectionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/categories'
    | '/cms'
    | '/profile'
    | '/sub-admin'
    | '/vendors'
    | '/$'
    | '/categories/create'
    | '/cms/banners'
    | '/products/products-list'
    | '/products/requests'
    | '/sub-admin/create-admin'
    | '/sub-admin/roles-permissions'
    | '/sub-admin/sub-admin-details'
    | '/tiers/create'
    | '/warehouses/create'
    | '/coins/$'
    | '/orders/$'
    | '/vendors/$vendorId'
    | '/warehouses/$warehouseId'
    | '/alerts'
    | '/categories/'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/orders'
    | '/promote-products'
    | '/reports'
    | '/sub-admin/'
    | '/tiers'
    | '/ugc-campaigns'
    | '/vendors/'
    | '/warehouse'
    | '/warehouses'
    | '/login'
    | '/scroll'
    | '/signup'
    | '/cms/banners/create'
    | '/cms/sections/create'
    | '/sub-admin/roles-permissions/$id'
    | '/sub-admin/roles-permissions/create'
    | '/sub-admin/sub-admin-details/$id'
    | '/categories/$categoryId/edit'
    | '/categories/$categoryId/view'
    | '/cms/home/create'
    | '/tiers/$tierId/edit'
    | '/warehouses/edit/$warehouseId'
    | '/cms/banners/'
    | '/cms/home'
    | '/cms/sections'
    | '/coins/summary'
    | '/coins/transactions'
    | '/orders/all'
    | '/orders/initiated'
    | '/orders/payment_confirmed'
    | '/products/add'
    | '/products/list'
    | '/sub-admin/roles-permissions/'
    | '/vendors/vendor-details'
    | '/sub-admin/roles-permissions/$id/edit'
    | '/cms/banners/edit/$bannerId'
    | '/cms/home/edit/$homeId'
    | '/cms/sections/$sectionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/cms'
    | '/profile'
    | '/$'
    | '/categories/create'
    | '/products/products-list'
    | '/products/requests'
    | '/sub-admin/create-admin'
    | '/sub-admin/sub-admin-details'
    | '/tiers/create'
    | '/warehouses/create'
    | '/coins/$'
    | '/orders/$'
    | '/vendors/$vendorId'
    | '/warehouses/$warehouseId'
    | '/alerts'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/orders'
    | '/promote-products'
    | '/reports'
    | '/sub-admin'
    | '/tiers'
    | '/ugc-campaigns'
    | '/vendors'
    | '/warehouse'
    | '/warehouses'
    | '/login'
    | '/scroll'
    | '/signup'
    | '/cms/banners/create'
    | '/cms/sections/create'
    | '/sub-admin/roles-permissions/$id'
    | '/sub-admin/roles-permissions/create'
    | '/sub-admin/sub-admin-details/$id'
    | '/categories/$categoryId/edit'
    | '/categories/$categoryId/view'
    | '/cms/home/create'
    | '/tiers/$tierId/edit'
    | '/warehouses/edit/$warehouseId'
    | '/cms/banners'
    | '/cms/home'
    | '/cms/sections'
    | '/coins/summary'
    | '/coins/transactions'
    | '/orders/all'
    | '/orders/initiated'
    | '/orders/payment_confirmed'
    | '/products/add'
    | '/products/list'
    | '/sub-admin/roles-permissions'
    | '/vendors/vendor-details'
    | '/sub-admin/roles-permissions/$id/edit'
    | '/cms/banners/edit/$bannerId'
    | '/cms/home/edit/$homeId'
    | '/cms/sections/$sectionId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/admin'
    | '/_app/categories'
    | '/_app/cms'
    | '/_app/profile'
    | '/_app/sub-admin'
    | '/_app/vendors'
    | '/_app/$'
    | '/_app/categories/create'
    | '/_app/cms/banners'
    | '/_app/products/products-list'
    | '/_app/products/requests'
    | '/_app/sub-admin/create-admin'
    | '/_app/sub-admin/roles-permissions'
    | '/_app/sub-admin/sub-admin-details'
    | '/_app/tiers/create'
    | '/_app/warehouses/create'
    | '/_app/coins/$'
    | '/_app/orders/$'
    | '/_app/vendors/$vendorId'
    | '/_app/warehouses/$warehouseId'
    | '/_app/alerts/'
    | '/_app/categories/'
    | '/_app/customers/'
    | '/_app/dashboard/'
    | '/_app/discounts/'
    | '/_app/orders/'
    | '/_app/promote-products/'
    | '/_app/reports/'
    | '/_app/sub-admin/'
    | '/_app/tiers/'
    | '/_app/ugc-campaigns/'
    | '/_app/vendors/'
    | '/_app/warehouse/'
    | '/_app/warehouses/'
    | '/_auth/login/'
    | '/_auth/scroll/'
    | '/_auth/signup/'
    | '/_app/cms/banners/create'
    | '/_app/cms/sections/create'
    | '/_app/sub-admin/roles-permissions/$id'
    | '/_app/sub-admin/roles-permissions/create'
    | '/_app/sub-admin/sub-admin-details/$id'
    | '/_app/categories/$categoryId/edit'
    | '/_app/categories/$categoryId/view'
    | '/_app/cms/home/create'
    | '/_app/tiers/$tierId/edit'
    | '/_app/warehouses/edit/$warehouseId'
    | '/_app/cms/banners/'
    | '/_app/cms/home/'
    | '/_app/cms/sections/'
    | '/_app/coins/summary/'
    | '/_app/coins/transactions/'
    | '/_app/orders/all/'
    | '/_app/orders/initiated/'
    | '/_app/orders/payment_confirmed/'
    | '/_app/products/add/'
    | '/_app/products/list/'
    | '/_app/sub-admin/roles-permissions/'
    | '/_app/vendors/vendor-details/'
    | '/_app/sub-admin/roles-permissions/$id/edit'
    | '/_app/cms/banners/edit/$bannerId'
    | '/_app/cms/home/edit/$homeId'
    | '/_app/cms/sections/$sectionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sub-admin': {
      id: '/_app/sub-admin'
      path: '/sub-admin'
      fullPath: '/sub-admin'
      preLoaderRoute: typeof AppSubAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cms': {
      id: '/_app/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AppCmsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/scroll/': {
      id: '/_auth/scroll/'
      path: '/scroll'
      fullPath: '/scroll'
      preLoaderRoute: typeof AuthScrollIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/warehouses/': {
      id: '/_app/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AppWarehousesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/warehouse/': {
      id: '/_app/warehouse/'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AppWarehouseIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vendors/': {
      id: '/_app/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppVendorsRouteRoute
    }
    '/_app/ugc-campaigns/': {
      id: '/_app/ugc-campaigns/'
      path: '/ugc-campaigns'
      fullPath: '/ugc-campaigns'
      preLoaderRoute: typeof AppUgcCampaignsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tiers/': {
      id: '/_app/tiers/'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof AppTiersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sub-admin/': {
      id: '/_app/sub-admin/'
      path: '/'
      fullPath: '/sub-admin/'
      preLoaderRoute: typeof AppSubAdminIndexRouteImport
      parentRoute: typeof AppSubAdminRouteRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/promote-products/': {
      id: '/_app/promote-products/'
      path: '/promote-products'
      fullPath: '/promote-products'
      preLoaderRoute: typeof AppPromoteProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discounts/': {
      id: '/_app/discounts/'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AppDiscountsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppCategoriesRouteRoute
    }
    '/_app/alerts/': {
      id: '/_app/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/warehouses/$warehouseId': {
      id: '/_app/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof AppWarehousesWarehouseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vendors/$vendorId': {
      id: '/_app/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AppVendorsVendorIdRouteImport
      parentRoute: typeof AppVendorsRouteRoute
    }
    '/_app/orders/$': {
      id: '/_app/orders/$'
      path: '/orders/$'
      fullPath: '/orders/$'
      preLoaderRoute: typeof AppOrdersSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/coins/$': {
      id: '/_app/coins/$'
      path: '/coins/$'
      fullPath: '/coins/$'
      preLoaderRoute: typeof AppCoinsSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/warehouses/create': {
      id: '/_app/warehouses/create'
      path: '/warehouses/create'
      fullPath: '/warehouses/create'
      preLoaderRoute: typeof AppWarehousesCreateRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tiers/create': {
      id: '/_app/tiers/create'
      path: '/tiers/create'
      fullPath: '/tiers/create'
      preLoaderRoute: typeof AppTiersCreateRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sub-admin/sub-admin-details': {
      id: '/_app/sub-admin/sub-admin-details'
      path: '/sub-admin-details'
      fullPath: '/sub-admin/sub-admin-details'
      preLoaderRoute: typeof AppSubAdminSubAdminDetailsRouteRouteImport
      parentRoute: typeof AppSubAdminRouteRoute
    }
    '/_app/sub-admin/roles-permissions': {
      id: '/_app/sub-admin/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/sub-admin/roles-permissions'
      preLoaderRoute: typeof AppSubAdminRolesPermissionsRouteRouteImport
      parentRoute: typeof AppSubAdminRouteRoute
    }
    '/_app/sub-admin/create-admin': {
      id: '/_app/sub-admin/create-admin'
      path: '/create-admin'
      fullPath: '/sub-admin/create-admin'
      preLoaderRoute: typeof AppSubAdminCreateAdminRouteRouteImport
      parentRoute: typeof AppSubAdminRouteRoute
    }
    '/_app/products/requests': {
      id: '/_app/products/requests'
      path: '/products/requests'
      fullPath: '/products/requests'
      preLoaderRoute: typeof AppProductsRequestsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/products-list': {
      id: '/_app/products/products-list'
      path: '/products/products-list'
      fullPath: '/products/products-list'
      preLoaderRoute: typeof AppProductsProductsListRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cms/banners': {
      id: '/_app/cms/banners'
      path: '/banners'
      fullPath: '/cms/banners'
      preLoaderRoute: typeof AppCmsBannersRouteRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/categories/create': {
      id: '/_app/categories/create'
      path: '/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof AppCategoriesCreateRouteRouteImport
      parentRoute: typeof AppCategoriesRouteRoute
    }
    '/_app/vendors/vendor-details/': {
      id: '/_app/vendors/vendor-details/'
      path: '/vendor-details'
      fullPath: '/vendors/vendor-details'
      preLoaderRoute: typeof AppVendorsVendorDetailsIndexRouteImport
      parentRoute: typeof AppVendorsRouteRoute
    }
    '/_app/sub-admin/roles-permissions/': {
      id: '/_app/sub-admin/roles-permissions/'
      path: '/'
      fullPath: '/sub-admin/roles-permissions/'
      preLoaderRoute: typeof AppSubAdminRolesPermissionsIndexRouteImport
      parentRoute: typeof AppSubAdminRolesPermissionsRouteRoute
    }
    '/_app/products/list/': {
      id: '/_app/products/list/'
      path: '/products/list'
      fullPath: '/products/list'
      preLoaderRoute: typeof AppProductsListIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/add/': {
      id: '/_app/products/add/'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof AppProductsAddIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/payment_confirmed/': {
      id: '/_app/orders/payment_confirmed/'
      path: '/orders/payment_confirmed'
      fullPath: '/orders/payment_confirmed'
      preLoaderRoute: typeof AppOrdersPayment_confirmedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/initiated/': {
      id: '/_app/orders/initiated/'
      path: '/orders/initiated'
      fullPath: '/orders/initiated'
      preLoaderRoute: typeof AppOrdersInitiatedIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/all/': {
      id: '/_app/orders/all/'
      path: '/orders/all'
      fullPath: '/orders/all'
      preLoaderRoute: typeof AppOrdersAllIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/coins/transactions/': {
      id: '/_app/coins/transactions/'
      path: '/coins/transactions'
      fullPath: '/coins/transactions'
      preLoaderRoute: typeof AppCoinsTransactionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/coins/summary/': {
      id: '/_app/coins/summary/'
      path: '/coins/summary'
      fullPath: '/coins/summary'
      preLoaderRoute: typeof AppCoinsSummaryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cms/sections/': {
      id: '/_app/cms/sections/'
      path: '/sections'
      fullPath: '/cms/sections'
      preLoaderRoute: typeof AppCmsSectionsIndexRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/cms/home/': {
      id: '/_app/cms/home/'
      path: '/home'
      fullPath: '/cms/home'
      preLoaderRoute: typeof AppCmsHomeIndexRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/cms/banners/': {
      id: '/_app/cms/banners/'
      path: '/'
      fullPath: '/cms/banners/'
      preLoaderRoute: typeof AppCmsBannersIndexRouteImport
      parentRoute: typeof AppCmsBannersRouteRoute
    }
    '/_app/warehouses/edit/$warehouseId': {
      id: '/_app/warehouses/edit/$warehouseId'
      path: '/warehouses/edit/$warehouseId'
      fullPath: '/warehouses/edit/$warehouseId'
      preLoaderRoute: typeof AppWarehousesEditWarehouseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tiers/$tierId/edit': {
      id: '/_app/tiers/$tierId/edit'
      path: '/tiers/$tierId/edit'
      fullPath: '/tiers/$tierId/edit'
      preLoaderRoute: typeof AppTiersTierIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cms/home/create': {
      id: '/_app/cms/home/create'
      path: '/home/create'
      fullPath: '/cms/home/create'
      preLoaderRoute: typeof AppCmsHomeCreateRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/categories/$categoryId/view': {
      id: '/_app/categories/$categoryId/view'
      path: '/$categoryId/view'
      fullPath: '/categories/$categoryId/view'
      preLoaderRoute: typeof AppCategoriesCategoryIdViewRouteImport
      parentRoute: typeof AppCategoriesRouteRoute
    }
    '/_app/categories/$categoryId/edit': {
      id: '/_app/categories/$categoryId/edit'
      path: '/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof AppCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AppCategoriesRouteRoute
    }
    '/_app/sub-admin/sub-admin-details/$id': {
      id: '/_app/sub-admin/sub-admin-details/$id'
      path: '/$id'
      fullPath: '/sub-admin/sub-admin-details/$id'
      preLoaderRoute: typeof AppSubAdminSubAdminDetailsIdRouteRouteImport
      parentRoute: typeof AppSubAdminSubAdminDetailsRouteRoute
    }
    '/_app/sub-admin/roles-permissions/create': {
      id: '/_app/sub-admin/roles-permissions/create'
      path: '/create'
      fullPath: '/sub-admin/roles-permissions/create'
      preLoaderRoute: typeof AppSubAdminRolesPermissionsCreateRouteRouteImport
      parentRoute: typeof AppSubAdminRolesPermissionsRouteRoute
    }
    '/_app/sub-admin/roles-permissions/$id': {
      id: '/_app/sub-admin/roles-permissions/$id'
      path: '/$id'
      fullPath: '/sub-admin/roles-permissions/$id'
      preLoaderRoute: typeof AppSubAdminRolesPermissionsIdRouteRouteImport
      parentRoute: typeof AppSubAdminRolesPermissionsRouteRoute
    }
    '/_app/cms/sections/create': {
      id: '/_app/cms/sections/create'
      path: '/sections/create'
      fullPath: '/cms/sections/create'
      preLoaderRoute: typeof AppCmsSectionsCreateRouteRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/cms/banners/create': {
      id: '/_app/cms/banners/create'
      path: '/create'
      fullPath: '/cms/banners/create'
      preLoaderRoute: typeof AppCmsBannersCreateRouteRouteImport
      parentRoute: typeof AppCmsBannersRouteRoute
    }
    '/_app/cms/sections/$sectionId/edit': {
      id: '/_app/cms/sections/$sectionId/edit'
      path: '/sections/$sectionId/edit'
      fullPath: '/cms/sections/$sectionId/edit'
      preLoaderRoute: typeof AppCmsSectionsSectionIdEditRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/cms/home/edit/$homeId': {
      id: '/_app/cms/home/edit/$homeId'
      path: '/home/edit/$homeId'
      fullPath: '/cms/home/edit/$homeId'
      preLoaderRoute: typeof AppCmsHomeEditHomeIdRouteImport
      parentRoute: typeof AppCmsRouteRoute
    }
    '/_app/cms/banners/edit/$bannerId': {
      id: '/_app/cms/banners/edit/$bannerId'
      path: '/edit/$bannerId'
      fullPath: '/cms/banners/edit/$bannerId'
      preLoaderRoute: typeof AppCmsBannersEditBannerIdRouteImport
      parentRoute: typeof AppCmsBannersRouteRoute
    }
    '/_app/sub-admin/roles-permissions/$id/edit': {
      id: '/_app/sub-admin/roles-permissions/$id/edit'
      path: '/edit'
      fullPath: '/sub-admin/roles-permissions/$id/edit'
      preLoaderRoute: typeof AppSubAdminRolesPermissionsIdEditRouteRouteImport
      parentRoute: typeof AppSubAdminRolesPermissionsIdRouteRoute
    }
  }
}

interface AppCategoriesRouteRouteChildren {
  AppCategoriesCreateRouteRoute: typeof AppCategoriesCreateRouteRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppCategoriesCategoryIdEditRoute: typeof AppCategoriesCategoryIdEditRoute
  AppCategoriesCategoryIdViewRoute: typeof AppCategoriesCategoryIdViewRoute
}

const AppCategoriesRouteRouteChildren: AppCategoriesRouteRouteChildren = {
  AppCategoriesCreateRouteRoute: AppCategoriesCreateRouteRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppCategoriesCategoryIdEditRoute: AppCategoriesCategoryIdEditRoute,
  AppCategoriesCategoryIdViewRoute: AppCategoriesCategoryIdViewRoute,
}

const AppCategoriesRouteRouteWithChildren =
  AppCategoriesRouteRoute._addFileChildren(AppCategoriesRouteRouteChildren)

interface AppCmsBannersRouteRouteChildren {
  AppCmsBannersCreateRouteRoute: typeof AppCmsBannersCreateRouteRoute
  AppCmsBannersIndexRoute: typeof AppCmsBannersIndexRoute
  AppCmsBannersEditBannerIdRoute: typeof AppCmsBannersEditBannerIdRoute
}

const AppCmsBannersRouteRouteChildren: AppCmsBannersRouteRouteChildren = {
  AppCmsBannersCreateRouteRoute: AppCmsBannersCreateRouteRoute,
  AppCmsBannersIndexRoute: AppCmsBannersIndexRoute,
  AppCmsBannersEditBannerIdRoute: AppCmsBannersEditBannerIdRoute,
}

const AppCmsBannersRouteRouteWithChildren =
  AppCmsBannersRouteRoute._addFileChildren(AppCmsBannersRouteRouteChildren)

interface AppCmsRouteRouteChildren {
  AppCmsBannersRouteRoute: typeof AppCmsBannersRouteRouteWithChildren
  AppCmsSectionsCreateRouteRoute: typeof AppCmsSectionsCreateRouteRoute
  AppCmsHomeCreateRoute: typeof AppCmsHomeCreateRoute
  AppCmsHomeIndexRoute: typeof AppCmsHomeIndexRoute
  AppCmsSectionsIndexRoute: typeof AppCmsSectionsIndexRoute
  AppCmsHomeEditHomeIdRoute: typeof AppCmsHomeEditHomeIdRoute
  AppCmsSectionsSectionIdEditRoute: typeof AppCmsSectionsSectionIdEditRoute
}

const AppCmsRouteRouteChildren: AppCmsRouteRouteChildren = {
  AppCmsBannersRouteRoute: AppCmsBannersRouteRouteWithChildren,
  AppCmsSectionsCreateRouteRoute: AppCmsSectionsCreateRouteRoute,
  AppCmsHomeCreateRoute: AppCmsHomeCreateRoute,
  AppCmsHomeIndexRoute: AppCmsHomeIndexRoute,
  AppCmsSectionsIndexRoute: AppCmsSectionsIndexRoute,
  AppCmsHomeEditHomeIdRoute: AppCmsHomeEditHomeIdRoute,
  AppCmsSectionsSectionIdEditRoute: AppCmsSectionsSectionIdEditRoute,
}

const AppCmsRouteRouteWithChildren = AppCmsRouteRoute._addFileChildren(
  AppCmsRouteRouteChildren,
)

interface AppSubAdminRolesPermissionsIdRouteRouteChildren {
  AppSubAdminRolesPermissionsIdEditRouteRoute: typeof AppSubAdminRolesPermissionsIdEditRouteRoute
}

const AppSubAdminRolesPermissionsIdRouteRouteChildren: AppSubAdminRolesPermissionsIdRouteRouteChildren =
  {
    AppSubAdminRolesPermissionsIdEditRouteRoute:
      AppSubAdminRolesPermissionsIdEditRouteRoute,
  }

const AppSubAdminRolesPermissionsIdRouteRouteWithChildren =
  AppSubAdminRolesPermissionsIdRouteRoute._addFileChildren(
    AppSubAdminRolesPermissionsIdRouteRouteChildren,
  )

interface AppSubAdminRolesPermissionsRouteRouteChildren {
  AppSubAdminRolesPermissionsIdRouteRoute: typeof AppSubAdminRolesPermissionsIdRouteRouteWithChildren
  AppSubAdminRolesPermissionsCreateRouteRoute: typeof AppSubAdminRolesPermissionsCreateRouteRoute
  AppSubAdminRolesPermissionsIndexRoute: typeof AppSubAdminRolesPermissionsIndexRoute
}

const AppSubAdminRolesPermissionsRouteRouteChildren: AppSubAdminRolesPermissionsRouteRouteChildren =
  {
    AppSubAdminRolesPermissionsIdRouteRoute:
      AppSubAdminRolesPermissionsIdRouteRouteWithChildren,
    AppSubAdminRolesPermissionsCreateRouteRoute:
      AppSubAdminRolesPermissionsCreateRouteRoute,
    AppSubAdminRolesPermissionsIndexRoute:
      AppSubAdminRolesPermissionsIndexRoute,
  }

const AppSubAdminRolesPermissionsRouteRouteWithChildren =
  AppSubAdminRolesPermissionsRouteRoute._addFileChildren(
    AppSubAdminRolesPermissionsRouteRouteChildren,
  )

interface AppSubAdminSubAdminDetailsRouteRouteChildren {
  AppSubAdminSubAdminDetailsIdRouteRoute: typeof AppSubAdminSubAdminDetailsIdRouteRoute
}

const AppSubAdminSubAdminDetailsRouteRouteChildren: AppSubAdminSubAdminDetailsRouteRouteChildren =
  {
    AppSubAdminSubAdminDetailsIdRouteRoute:
      AppSubAdminSubAdminDetailsIdRouteRoute,
  }

const AppSubAdminSubAdminDetailsRouteRouteWithChildren =
  AppSubAdminSubAdminDetailsRouteRoute._addFileChildren(
    AppSubAdminSubAdminDetailsRouteRouteChildren,
  )

interface AppSubAdminRouteRouteChildren {
  AppSubAdminCreateAdminRouteRoute: typeof AppSubAdminCreateAdminRouteRoute
  AppSubAdminRolesPermissionsRouteRoute: typeof AppSubAdminRolesPermissionsRouteRouteWithChildren
  AppSubAdminSubAdminDetailsRouteRoute: typeof AppSubAdminSubAdminDetailsRouteRouteWithChildren
  AppSubAdminIndexRoute: typeof AppSubAdminIndexRoute
}

const AppSubAdminRouteRouteChildren: AppSubAdminRouteRouteChildren = {
  AppSubAdminCreateAdminRouteRoute: AppSubAdminCreateAdminRouteRoute,
  AppSubAdminRolesPermissionsRouteRoute:
    AppSubAdminRolesPermissionsRouteRouteWithChildren,
  AppSubAdminSubAdminDetailsRouteRoute:
    AppSubAdminSubAdminDetailsRouteRouteWithChildren,
  AppSubAdminIndexRoute: AppSubAdminIndexRoute,
}

const AppSubAdminRouteRouteWithChildren =
  AppSubAdminRouteRoute._addFileChildren(AppSubAdminRouteRouteChildren)

interface AppVendorsRouteRouteChildren {
  AppVendorsVendorIdRoute: typeof AppVendorsVendorIdRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
  AppVendorsVendorDetailsIndexRoute: typeof AppVendorsVendorDetailsIndexRoute
}

const AppVendorsRouteRouteChildren: AppVendorsRouteRouteChildren = {
  AppVendorsVendorIdRoute: AppVendorsVendorIdRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
  AppVendorsVendorDetailsIndexRoute: AppVendorsVendorDetailsIndexRoute,
}

const AppVendorsRouteRouteWithChildren = AppVendorsRouteRoute._addFileChildren(
  AppVendorsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRoute
  AppCategoriesRouteRoute: typeof AppCategoriesRouteRouteWithChildren
  AppCmsRouteRoute: typeof AppCmsRouteRouteWithChildren
  AppProfileRouteRoute: typeof AppProfileRouteRoute
  AppSubAdminRouteRoute: typeof AppSubAdminRouteRouteWithChildren
  AppVendorsRouteRoute: typeof AppVendorsRouteRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
  AppProductsProductsListRouteRoute: typeof AppProductsProductsListRouteRoute
  AppProductsRequestsRouteRoute: typeof AppProductsRequestsRouteRoute
  AppTiersCreateRouteRoute: typeof AppTiersCreateRouteRoute
  AppWarehousesCreateRouteRoute: typeof AppWarehousesCreateRouteRoute
  AppCoinsSplatRoute: typeof AppCoinsSplatRoute
  AppOrdersSplatRoute: typeof AppOrdersSplatRoute
  AppWarehousesWarehouseIdRoute: typeof AppWarehousesWarehouseIdRoute
  AppAlertsIndexRoute: typeof AppAlertsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDiscountsIndexRoute: typeof AppDiscountsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPromoteProductsIndexRoute: typeof AppPromoteProductsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppTiersIndexRoute: typeof AppTiersIndexRoute
  AppUgcCampaignsIndexRoute: typeof AppUgcCampaignsIndexRoute
  AppWarehouseIndexRoute: typeof AppWarehouseIndexRoute
  AppWarehousesIndexRoute: typeof AppWarehousesIndexRoute
  AppTiersTierIdEditRoute: typeof AppTiersTierIdEditRoute
  AppWarehousesEditWarehouseIdRoute: typeof AppWarehousesEditWarehouseIdRoute
  AppCoinsSummaryIndexRoute: typeof AppCoinsSummaryIndexRoute
  AppCoinsTransactionsIndexRoute: typeof AppCoinsTransactionsIndexRoute
  AppOrdersAllIndexRoute: typeof AppOrdersAllIndexRoute
  AppOrdersInitiatedIndexRoute: typeof AppOrdersInitiatedIndexRoute
  AppOrdersPayment_confirmedIndexRoute: typeof AppOrdersPayment_confirmedIndexRoute
  AppProductsAddIndexRoute: typeof AppProductsAddIndexRoute
  AppProductsListIndexRoute: typeof AppProductsListIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRoute,
  AppCategoriesRouteRoute: AppCategoriesRouteRouteWithChildren,
  AppCmsRouteRoute: AppCmsRouteRouteWithChildren,
  AppProfileRouteRoute: AppProfileRouteRoute,
  AppSubAdminRouteRoute: AppSubAdminRouteRouteWithChildren,
  AppVendorsRouteRoute: AppVendorsRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
  AppProductsProductsListRouteRoute: AppProductsProductsListRouteRoute,
  AppProductsRequestsRouteRoute: AppProductsRequestsRouteRoute,
  AppTiersCreateRouteRoute: AppTiersCreateRouteRoute,
  AppWarehousesCreateRouteRoute: AppWarehousesCreateRouteRoute,
  AppCoinsSplatRoute: AppCoinsSplatRoute,
  AppOrdersSplatRoute: AppOrdersSplatRoute,
  AppWarehousesWarehouseIdRoute: AppWarehousesWarehouseIdRoute,
  AppAlertsIndexRoute: AppAlertsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDiscountsIndexRoute: AppDiscountsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPromoteProductsIndexRoute: AppPromoteProductsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppTiersIndexRoute: AppTiersIndexRoute,
  AppUgcCampaignsIndexRoute: AppUgcCampaignsIndexRoute,
  AppWarehouseIndexRoute: AppWarehouseIndexRoute,
  AppWarehousesIndexRoute: AppWarehousesIndexRoute,
  AppTiersTierIdEditRoute: AppTiersTierIdEditRoute,
  AppWarehousesEditWarehouseIdRoute: AppWarehousesEditWarehouseIdRoute,
  AppCoinsSummaryIndexRoute: AppCoinsSummaryIndexRoute,
  AppCoinsTransactionsIndexRoute: AppCoinsTransactionsIndexRoute,
  AppOrdersAllIndexRoute: AppOrdersAllIndexRoute,
  AppOrdersInitiatedIndexRoute: AppOrdersInitiatedIndexRoute,
  AppOrdersPayment_confirmedIndexRoute: AppOrdersPayment_confirmedIndexRoute,
  AppProductsAddIndexRoute: AppProductsAddIndexRoute,
  AppProductsListIndexRoute: AppProductsListIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthScrollIndexRoute: typeof AuthScrollIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthScrollIndexRoute: AuthScrollIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
